[package]
name = "shader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "brot3's GPU shader"

# TODO: It would be nice to build dylib only on spirv and rlib on host builds.
# This is not currently supported by cargo; https://github.com/rust-lang/cargo/issues/12260 refers.
[lib]
crate-type = ["dylib", "rlib"]

[[bench]]
name = "shader"
harness = false

[[bench]]
name = "colour_conversion"
harness = false

[features]
## Emulate push constants. Useful if the GPU does not support PUSH_CONSTANTS.
emulate_constants = []

[dependencies]
const-default = { workspace = true }
document-features = { workspace = true }
float_eq = { workspace = true }
paste = { workspace = true }
shader_common = { workspace = true }
spirv-std = { workspace = true }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
dashu = { workspace = true }
dashu-float = { workspace = true }
glam = { workspace = true, features = ["std"] }

[lints]
workspace = true

[dev-dependencies]
derive_more = { workspace = true, features = ["debug"] }
divan = { workspace = true }
glam = { workspace = true, default-features = false, features = ["std"] }
pretty_assertions = { workspace = true }
strum = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["glam"]
