[package]
name = "shader"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "brot3's GPU shader"

# TODO: It would be nice to build dylib only on spirv and rlib on host builds.
# This is not currently supported by cargo; https://github.com/rust-lang/cargo/issues/12260 refers.
[lib]
crate-type = ["dylib", "rlib"]

[[bench]]
name = "shader"
harness = false

[[bench]]
name = "colour_conversion"
harness = false

[features]
## Emulate push constants. Useful if the GPU does not support PUSH_CONSTANTS.
emulate_constants = []

[dependencies]
bitflags = { workspace = true, features = ["bytemuck"] }
build_assert = { workspace = true }
bytemuck = { workspace = true, features = ["derive"] }
const-default = { workspace = true }
derive_more = { workspace = true, default-features = false, features = ["constructor", "display"] }
document-features = { workspace = true }
float_eq = { workspace = true }
paste = { workspace = true }
spirv-std = { workspace = true }

[target.'cfg(target_arch = "spirv")'.dependencies]
abels-complex = { workspace = true, features = ["libm", "glam"] }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
dashu = { workspace = true }
dashu-float = { workspace = true }
glam = { workspace = true, features = ["std", "bytemuck"] }
abels-complex = { workspace = true, features = ["std", "glam"] }
clap = { workspace = true, features = ["derive"] }
num-derive = "0.4.2"
num-traits = { workspace = true }
serde = { workspace = true }
strum = { version = "0.27.2", default-features = false, features = ["derive"] }

[lints]
workspace = true

[dev-dependencies]
derive_more = { workspace = true, features = ["debug"] }
divan = { workspace = true }
float_eq = { workspace = true }
glam = { workspace = true, default-features = false, features = ["std"] }
pretty_assertions = { workspace = true }
strum = { workspace = true }
