// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Slider, Button } from "std-widgets.slint";
export struct Tile { x: length, y: length, tile: image}

export component MainUI inherits Window {
    callback flicked(length, length);
    callback zoom-changed(float);
    callback zoom-in(length, length);
    callback zoom-out(length, length);
    callback resegment-clicked();
    min-height: 500px;
    min-width: 500px;

    out property <length> visible_width: fli.width;
    out property <length> visible_height: fli.height;

    in-out property <float> zoom <=> sli.value;

    in property <[Tile]> tiles;

    in property <string> window-title <=> self.title;

    // ox,oy: Viewport offsets within the visible segment (these are usually negative?)
    // width, height: viewport size
    public function set_viewport(ox: length, oy: length, width: length, height: length) {
        fli.viewport-x = ox;
        fli.viewport-y = oy;
        fli.viewport-width = width;
        fli.viewport-height = height;
    }

    VerticalLayout {
        fli := Flickable {
            for t in tiles: Image {
                x: t.x;
                y: t.y;
                source: t.tile;
            }
            flicked => {
                root.flicked(fli.viewport-x, fli.viewport-y);
            }
            TouchArea {
                scroll-event(e) => {
                    if e.delta-y > 0 {
                        root.zoom-in(self.mouse-x + fli.viewport-x, self.mouse-y + fli.viewport-y);
                        return accept;
                    } else if e.delta-y < 0 {
                        root.zoom-out(self.mouse-x + fli.viewport-x, self.mouse-y + fli.viewport-y);
                        return accept;
                    }
                    return reject;
                }
            }
        }

        HorizontalLayout {
            sli := Slider {
                minimum: 1;
                maximum: 45; // !!! Must match UI_MAX_ZOOM_LEVEL
                released => {
                    zoom-changed(self.value);
                }
            }
        }
    }

    /*
    btn := Button { // TECHDEBT This was put in for testing resegmentation; should be made automatic.
        x: 0;
        y: fli.y + (fli.height) - (self.height) - 3px;
        text: "Resegment";
        clicked => {
            root.resegment-clicked();
        }
    }
    */

    // HUD display data
    in property <string> algorithm;
    in property <string> colourer;
    in property <int> max_iter;
    in property <string> origin;
    in property <string> axes;
    in property <string> zoom_readout;

    Rectangle {
        info := Text {

            text: algorithm + " (max=" + max_iter + ") :: " + colourer
                + "    origin=" + origin
                + "    zoom=" + zoom_readout
                + "    axes: " + axes;

            font-family: "Inter"; // TODO how to ensure font is present?
            font-size: 18px;
            font-weight: 900;
            color: white;
            opacity: 1.0;
            z: 10.0;
            horizontal-alignment: TextHorizontalAlignment.center;
            wrap: TextWrap.word-wrap;
            overflow: TextOverflow.elide;
            width: 100%;
            y: fli.y + (fli.height) - (self.height);
            // this may at some point gain a TouchArea to allow editing
        }
        Rectangle {
            width: 100%;
            height <=> info.height;
            x <=> info.x;
            y <=> info.y;
            z: 1.0;
            background: #111;
            opacity: 0.6;
        }
    }
}