# see https://docs.codecov.com/docs/components

component_management:
  default_rules: # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        threshold: 5
  individual_components:
    - component_id: engine # this is an identifier that should not be changed
      name: engine # this is a display name, and can be changed freely
      paths:
        - engine/**
    - component_id: cli
      name: cli
      paths:
        - cli/**
    - component_id: ui
      name: ui
      paths:
        - ui/**
