[package]
name = "shader_builder"
version.workspace = true
authors.workspace = true
edition.workspace = true
license = "MIT"
publish = false
description = "Builds the brot3 shader crate"

[[bin]]
name = "shader_builder"
test = false
bench = false
doc = false

[dependencies]
build-print.workspace = true
spirv-builder.workspace = true
thiserror.workspace = true

[lints]
workspace = true
