[package]
name = "shader_builder"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license = "MIT"
publish = false
description = "Builds the brot3 shader crate"

[[bin]]
name = "shader_builder"
test = false
bench = false
doc = false

[features]
# By default, the use-compiled-tools is enabled, as doesn't require additional
# setup steps for the user. This does however mean that you will need to disable
# default features and explicitly enable `use-installed-tools` if you are using
# this in an environment with spirv-tools in PATH, and you don't want to take
# the compile time cost
default = ["use-compiled-tools"]
# If enabled, uses spirv-tools binaries installed in PATH, instead of
# compiling and linking the spirv-tools C++ code
use-installed-tools = ["spirv-builder/use-installed-tools"]
# If enabled will compile and link the C++ code for the spirv tools. The compiled
# version is preferred if both this and `use-installed-tools` are enabled
use-compiled-tools = ["spirv-builder/use-compiled-tools"]

[dependencies]
build-print.workspace = true
dunce = { workspace = true }
spirv-builder.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true

[lints]
workspace = true
