[package]
name = "shader_builder"
version = "0.0.0"
publish = false
authors.workspace = true
edition.workspace = true
license = "MIT"

[[bin]]
name = "shader_builder"
test = false

[dependencies]
spirv-builder.workspace = true
