[package]
name = "brot3"
version = "0.0.0"
edition = "2021"
authors = ["Ross Younger <crazyscot@gmail.com>"]
description = "Yet Another Fractal Plotter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.4"
anyhow = "1.0.79"
array2d = "0.3.2"
assert_float_eq = "1.1.3"
clap = { version = "4.4.18", features = ["wrap_help", "cargo", "derive"] }
num-complex = "0.4.4"
png = "0.17.11"
strum = "0.25.0"
strum_macros = "0.25.3"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "initial"
harness = false