[workspace]
members = [
    "engine",
]
resolver = "2"
package.edition = "2021"
package.authors = ["Ross Younger <crazyscot@gmail.com>"]
package.version = "0.1.0"

[profile.ci]
inherits = "dev"
opt-level = 0
debug = 0
incremental = false
codegen-units = 256

[profile.release]
# See https://nnethercote.github.io/perf-book/build-configuration.html
codegen-units = 1
lto = "thin"
