[workspace]
members = ["easy-shader-runner", "lib", "shader_builder", "ui", "xtask"]
resolver = "2"

[workspace.package]
version = "3.6.1"
authors = ["Ross Younger <crazyscot@gmail.com>"]
categories = ["graphics", "mathematics"]
edition = "2024"
keywords = ["fractal", "mandelbrot"]
license = "MIT"
repository = "https://github.com/crazyscot/brot3/"

[workspace.dependencies]
abels-complex = { version = "0.6.3", default-features = false }
anyhow = "1.0.102"
assert_matches = "1.5.0"
average = "0.17.0"
bitflags = "2.13.1"
brot3-lib = { path = "lib" }
build-print = "1.0.1"
bytemuck = { version = "1.25.1", default-features = false }
cfg-if = "1.0.4"
cfg_aliases = "0.2.1"
chrono = { version = "0.4.44", default-features = false }
clap = { version = "4.6.2", features = ["derive"] }
const-default = { version = "1.0.0", default-features = false }
criterion = "0.8.2"
dashu = { version = "0.5.0", default-features = false }
dashu-float = { version = "0.5.0", default-features = false }
derive_more = { version = "2.1.1", default-features = false }
dirs = "6.0.0"
document-features = "0.2.12"
dunce = "1.0.5"
easy-cast = { version = "0.6.1", default-features = false }
easy-shader-runner = { path = "easy-shader-runner", default-features = false }
egui = "0.35.0"
egui-wgpu = "0.35.0"
egui-winit = { version = "0.35.0", default-features = false }
egui_extras = "0.34.2"
env_logger = "0.11.11"
flate2 = "1.1.9"
float_eq = { version = "1.0.1", default-features = false }
futures = { version = "0.3.32", default-features = false }
futures-channel = "0.3.32"
glam = { version = "0.32.1", default-features = false }
gungraun = "0.19.2"
image = { version = "0.25.10", default-features = false }
itertools = "0.15.0"
log = "0.4.31"
mimalloc = "0.1.52"
num-derive = "0.5.1"
num-traits = { version = "0.2.19", default-features = false, features = ["libm"] }
paste = "1.0.15"
pico-args = "0.5.0"
png = "0.18.1"
pretty_assertions = "1.4.1"
rayon = "1.12.0"
rfd = "0.17.2"
scopeguard = "1.2.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.150"
strum = { version = "0.28.0", default-features = false }
thiserror = { version = "2.0.18", default-features = false }
tokio = "1.52.3"
wgpu = { version = "30.0", default-features = false }
windows = { version = "0.62.2", default-features = false }

[workspace.dependencies.spirv-std]
git = "https://github.com/Rust-GPU/rust-gpu"
rev = "c904e5c039676df3409dd7aa61119102109af921"

[patch.'https://github.com/Rust-GPU/rust-gpu']
# TEMP: abels-complex 0.5 forces glam 0.32; rust-gpu currently requires glam >=0.30.8
# N.B. easy-shader-runner also uses glam
glam = { version = "0.32.1" }

[workspace.dependencies.spirv-builder]
git = "https://github.com/Rust-GPU/rust-gpu"
rev = "c904e5c039676df3409dd7aa61119102109af921"
default-features = false

[workspace.lints.rust]
dead_code = "warn"
elided_lifetimes_in_paths = "deny"
meta_variable_misuse = "deny"
missing_abi = "deny"
missing_copy_implementations = "deny"
missing_debug_implementations = "deny"
missing_docs = "warn"
non_ascii_idents = "deny"
single_use_lifetimes = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unexpected_cfgs = { level = "allow", check-cfg = ['cfg(target_arch, values("spirv"))', 'cfg(coverage_nightly)'] }
unreachable_pub = "deny"
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"
# unused_crate_dependencies = "deny" # false positives
unused_extern_crates = "deny"
unused_lifetimes = "deny"
unused_results = "deny"
variant_size_differences = "deny"

[workspace.lints.clippy]
missing_errors_doc = "allow"
missing_panics_doc = "allow"
pedantic = { level = "deny", priority = -1 }
# codegen-units = 1

[profile.release]
lto = "thin"
debug = "line-tables-only"
strip = "debuginfo"

[profile.dev]
package.spirv-tools-sys.opt-level = 1

# I would really like to set this for spirv builds only.
# At present this is achieved having shader_builder set an env var.
# [profile.release.package."brot3-lib"]
# debug = false

[workspace.metadata.cargo-shear]
ignored = [
  "image", # used as a mixin, not directly referenced
]
