[package]
name = "brot3"
version = "0.0.0"
edition = "2021"
authors = ["Ross Younger <crazyscot@gmail.com>"]
description = "Yet Another Fractal Plotter"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anstyle = "1.0.5"
anyhow = "1.0.79"
array2d = "0.3.2"
assert_float_eq = "1.1.3"
clap = { version = "4.4.18", features = ["wrap_help", "cargo", "derive"] }
enum_delegate = "0.2.0"
num-complex = "0.4.4"
palette = "0.7.4"
png = "0.17.11"
rayon = "1.8.1"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
iai-callgrind = "0.10.2"

[[bench]]
name = "colourer"
harness = false

[[bench]]
name = "fractal"
harness = false

[[bench]]
name = "iai"
harness = false
