[workspace]
members = [
    "cli",
    "engine",
    "ui/src-tauri",
]
resolver = "2"
package.edition = "2021"
package.authors = ["Ross Younger <crazyscot@gmail.com>"]
package.version = "0.1.0"

[profile.ci]
inherits = "dev"
opt-level = 0
debug = 0
incremental = false
codegen-units = 256

[profile.release]
# See https://nnethercote.github.io/perf-book/build-configuration.html
codegen-units = 1
lto = "thin"

[workspace.dependencies]
anyhow = "1.0.80"
clap = "4.5.1"
png = "0.17.13"
rayon = "1.8.1"
strum = { version = "0.26.1", features = ["derive"] }
strum_macros = "0.26.1"

[workspace.lints.rust]
elided_lifetimes_in_paths = "deny"
meta_variable_misuse = "deny"
missing_abi = "deny"
missing_copy_implementations = "deny"
missing_debug_implementations = "deny"
missing_docs = "warn"
non_ascii_idents = "deny"
single_use_lifetimes = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "deny"
unreachable_pub = "deny"
# unused_crate_dependencies = "deny" # false positives
unused_extern_crates = "deny"
unused_lifetimes = "deny"
unused_results = "deny"
unused_tuple_struct_fields = "warn"
variant_size_differences = "deny"

[workspace.lints.clippy]
pedantic = "deny"
missing_errors_doc = "allow"
