[workspace]
members = [
    "engine",
]
resolver = "2"

[profile.ci]
inherits = "dev"
opt-level = 0
debug = 0
incremental = false
codegen-units = 256

[profile.release]
# See https://nnethercote.github.io/perf-book/build-configuration.html
codegen-units = 1
lto = "thin"
