disallowed-types = [
    { path = "std::collections::HashMap", reason = "Non-deterministic time, consider BTreeMap" },
    { path = "std::collections::HashSet", reason = "Non-deterministic time, consider BTreeSet" },
]
