# This is based on the rust-gpu recommended toolchain, see https://github.com/Rust-GPU/rust-gpu/blob/main/rust-toolchain.toml

# When changing the toolchain version, be sure to check the repo thoroughly and update all usese!
#   rust-toolchain.toml
#   rust-toolchain-fmt.toml
#   .github/workflows/* (multiple instances)
#   scripts/* (multiple instances)

[toolchain]
channel = "nightly-2026-04-11"
components = ["rust-src", "rustc-dev", "llvm-tools", "rust-analyzer", "rustfmt"]
