[package]
name = "easy-shader-runner"
version = "0.0.0"
authors = ["Abel <abel465@gmail.com>"]
edition.workspace = true
keywords = ["shaders", "rust-gpu", "egui"]
license = "MIT"
publish = false
repository = "https://github.com/abel465/easy-shader-runner"
description = "Use rust shaders and egui on the web and native"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["hot-reload-shader", "use-compiled-tools"]
runtime-compilation = ["dep:spirv-builder"]
hot-reload-shader = ["spirv-builder/watch"]
emulate_constants = []
compute = []
# If enabled, spirv-builder uses spirv-tools binaries installed in PATH, instead of
# compiling and linking the spirv-tools C++ code
use-installed-tools = ["spirv-builder?/use-installed-tools"]
# If enabled, spirv-builder will compile and link the C++ code for the spirv tools
use-compiled-tools = ["spirv-builder?/use-compiled-tools"]

[dependencies]
bytemuck.workspace = true
cfg-if.workspace = true
easy-cast.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
glam = { workspace = true, features = ["std"] }
log.workspace = true
num-traits.workspace = true
thiserror.workspace = true

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
egui-winit = { workspace = true, default-features = true }
env_logger.workspace = true
futures = { workspace = true, default-features = false, features = ["executor"] }
spirv-builder = { workspace = true, optional = true }
wgpu = { workspace = true, default-features = false, features = ["spirv", "vulkan", "dx12", "metal"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
egui-winit = { workspace = true, default-features = false }
wgpu = { workspace = true, default-features = false, features = ["spirv", "webgpu"] }
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.77"

[lints]
workspace = true
