[package]
name = "brot3-cli"
edition.workspace = true
authors.workspace = true
version.workspace = true

[dependencies]
brot3-engine = { path = "../engine" }
clap = { version = "4.4.18", features = ["wrap_help", "derive"] }
anyhow = "1.0.79"
