[package]
name = "util"
version.workspace = true
authors = ["Ross Younger <crazyscot@gmail.com>", "Abel <abel465@gmail.com>"]
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license = "MIT"
publish = false
repository.workspace = true
description = "Utilities used by the brot3 ui (separate crate for efficient testing)"

[lib]
bench = false

[dependencies]
bytemuck.workspace = true
num-traits.workspace = true

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
dashu = { workspace = true, features = ["serde"] }
dashu-float = { workspace = true }
glam = { workspace = true, features = ["std", "bytemuck"] }

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions.workspace = true

[lints]
workspace = true
