[package]
name = "util"
description = "Utilities used by the brot3 ui (separate crate for efficient testing)"
authors = ["Ross Younger <crazyscot@gmail.com>", "Abel <abel465@gmail.com>"]
license = "MIT"
version.workspace = true
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[lib]
bench = false

[dependencies]
dashu = { workspace = true }
dashu-float = { workspace = true }
glam = { workspace = true, features = ["std"] }

[dev-dependencies]
float_eq = { workspace = true }
pretty_assertions.workspace = true

[lints]
workspace = true
