[package]
name = "brot3-lib"
version.workspace = true
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license = "MIT"
publish = false
repository.workspace = true
description = "brot3's engine"

# TODO: It would be nice to build dylib only on spirv and rlib on host builds.
# This is not currently supported by cargo; https://github.com/rust-lang/cargo/issues/12260 refers.
[lib]
crate-type = ["dylib", "rlib"]

[[bench]]
name = "cycles"
harness = false

[[bench]]
name = "criterion"
harness = false

[features]
## Emulate push constants. Useful if the GPU does not support PUSH_CONSTANTS.
emulate_constants = []

[dependencies]
bitflags = { workspace = true, features = ["bytemuck"] }
bytemuck = { workspace = true, features = ["derive"] }
const-default = { workspace = true }
derive_more = { workspace = true, default-features = false, features = ["constructor", "display", "eq"] }
document-features = { workspace = true }
easy-cast = { workspace = true, default-features = false }
float_eq.workspace = true
num-traits.workspace = true
paste = { workspace = true }
spirv-std = { workspace = true }

[target.'cfg(target_arch = "spirv")'.dependencies]
abels-complex = { workspace = true, features = ["libm", "glam"] }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
abels-complex = { workspace = true, features = ["std", "glam"] }
clap = { workspace = true, features = ["derive"] }
dashu-float = { workspace = true }
dashu = { workspace = true, features = ["serde"] }
glam = { workspace = true, features = ["std", "bytemuck"] }
log = { workspace = true }
num-derive = { workspace = true }
png = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, default-features = false, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }
derive_more = { workspace = true, features = ["debug"] }
easy-cast = { workspace = true, default-features = true }
gungraun = { workspace = true }
pretty_assertions = { workspace = true }
strum = { workspace = true }

[build-dependencies]
cfg_aliases = { workspace = true }

[lints]
workspace = true

[package.metadata.cargo-machete]
ignored = [
  "cfg_aliases", # false positive
]
