[future-incompat-report]
frequency = 'always'

[alias]
xtask = "run --package xtask --"

# On Windows MSVC, statically link the C runtime so that the resulting EXE does
# not depend on the vcruntime DLL.
[target.'cfg(target_env = "msvc")']
rustflags = ["-C", "target-feature=+crt-static"]

# [target.'cfg(target_os="linux")']
# Caution! Unconditionally specifying mold or wild breaks builds where these are not installed.

# To speed up local builds, set up your own ~/.cargo/config.toml something like this:
#
#   [target.'cfg(target_os="linux")']
#   linker = "clang"
#   rustflags = ["-C", "link-arg=--ld-path=mold"]
#
# You might also try wild (Linux only at the time of writing). `cargo install --locked wild-linker`
# On Windows, lld might be worthwhile.
