[package]
name = "shader_common"
version.workspace = true
authors = ["Ross Younger <crazyscot@gmail.com>"]
edition.workspace = true
license.workspace = true
publish = false
description = "Common types shared by the brot3 shader and UI crates"

[lib]
bench = false

[dependencies]
bitflags = { workspace = true, features = ["bytemuck"] }
bytemuck = { workspace = true, features = ["derive"] }
const-default = { workspace = true }
spirv-std = { workspace = true }

[target.'cfg(target_arch = "spirv")'.dependencies]
abels-complex = { workspace = true, features = ["libm", "glam"] }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
abels-complex = { workspace = true, features = ["std", "glam"] }
clap = { workspace = true, features = ["derive"] }
glam = { workspace = true, features = ["bytemuck"] }
num-derive = "0.4.2"
num-traits = { workspace = true }
strum = { version = "0.27.2", default-features = false, features = ["derive"] }

[lints]
workspace = true

[dev-dependencies]
float_eq = { workspace = true }
pretty_assertions = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["glam"]
