#!/bin/sh -e

# Script prerequisites:
#   Rust toolchain
#   lcov package (for genhtml)
#   cargo install cargo-llvm-cov

COVERAGE_DIR=target/coverage
NIGHTLY="+nightly-2026-04-11"

# CAUTION: llvm-cov sets cfg(nightly) by default.
# Sometimes dependencies can have older MSRVs and since-removed config options.
# These would choke the analysis.

PREFIX=$(pwd)

mkdir -p $COVERAGE_DIR
# shellcheck disable=SC2086
# N.B. nextest doesn't support doctests yet
cargo ${NIGHTLY} llvm-cov --locked --frozen --all-features --lcov --output-path $COVERAGE_DIR/lcov.info --show-instantiations nextest -p brot3-lib
genhtml $COVERAGE_DIR/lcov.info -o $COVERAGE_DIR/html --prefix ${PREFIX}
echo Coverage written to $COVERAGE_DIR/html
