#!/bin/bash -e

# Tools you may need to install:
#   cargo install --locked cargo-machete cargo-shear dprint typos-cli@1.39.0

typos
cargo fmt --all --check
dprint check
cargo machete --with-metadata
cargo shear --locked
