[package]
name = "builder"
version = "0.0.0"
publish = false
authors = ["Abel <abel465@gmail.com>"]
edition.workspace = true
license = "MIT"

[[bin]]
name = "builder"
test = false

[dependencies]
spirv-builder.workspace = true
