[package]
name = "base"
version.workspace = true
authors = ["Ross Younger <crazyscot@gmail.com>", "Abel <abel465@gmail.com>"]
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license = "MIT"
publish = false
repository.workspace = true
description = "Shared definitions and support code for brot3 (separate crate for efficient testing)"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
const-default = { workspace = true }
num-traits.workspace = true

[target.'cfg(target_arch = "spirv")'.dependencies]

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
num-derive = "0.4.2"
strum = { version = "0.28.0", default-features = false, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
dashu = { workspace = true, features = ["serde"] }
dashu-float = { workspace = true }
glam = { workspace = true, features = ["std", "bytemuck"] }

[dev-dependencies]
assert_matches = "1.5.0"
pretty_assertions = { workspace = true }
strum = { workspace = true }

[lints]
workspace = true
