[package]
name = "brot3-ui"
version.workspace = true
authors.workspace = true
default-run = "brot3"
edition.workspace = true
license.workspace = true
publish = false
description = "Interactive fractal explorer"

[[bin]]
name = "brot3"
test = false
doc = false
bench = false

[lib]
test = false
doc = false
doctest = false
bench = false

[features]
default = ["ui"]
runtime-compilation = ["easy-shader-runner/runtime-compilation"]
hot-reload-shader = ["easy-shader-runner/hot-reload-shader"]
## For use in special CI jobs only
suppress-shader-build = []
ui = [
  "easy-shader-runner",
  "egui_extras",
  "rfd",
  "bytemuck",
  "dirs",
  "chrono",
  "scopeguard",
  "futures",
]

[dependencies]
brot3-lib = { workspace = true }
bytemuck = { workspace = true, optional = true }
cfg-if = { workspace = true }
chrono = { workspace = true, features = ["clock"], optional = true }
clap = { workspace = true, features = ["derive", "wrap_help"] }
derive_more = { workspace = true, default-features = false, features = ["debug"] }
dirs = { workspace = true, optional = true }
easy-cast = { workspace = true, features = ["std"] }
egui_extras = { workspace = true, features = ["image"], optional = true }
env_logger = { workspace = true }
futures = { workspace = true, optional = true }
futures-channel = { workspace = true }
glam = { workspace = true }
# image is indirectly used, for unpicking PNGs
image = { workspace = true, features = ["png"] }
itertools = "0.14.0"
log = { workspace = true }
mimalloc = { workspace = true }
png = { workspace = true }
rayon = { workspace = true }
rfd = { workspace = true, optional = true }
scopeguard = { workspace = true, optional = true }
serde_json.workspace = true
strum = { workspace = true, features = ["std"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
wgpu.workspace = true

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
easy-shader-runner = { workspace = true, default-features = false, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# CAUTION: wasm builds are not currently tested.
# wasm-bindgen-futures = "0.4.55"
easy-shader-runner = { workspace = true, default-features = false, features = ["emulate_constants"], optional = true }

[build-dependencies]
build-print = { workspace = true }
cfg_aliases = { workspace = true }

[dev-dependencies]
average = { workspace = true }

[lints]
workspace = true

[package.metadata.deb]
name = "brot3"
default-features = false # no runtime compilation
section = "mathematics"
extended-description = """\
An interactive fractal explorer that uses the GPU.
"""
assets = [
  [
    "target/release/brot3",
    "usr/bin/",
    "755",
  ],

  [
    "../README.md",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../LICENSE",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../target/misc/changelog.md.gz",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../target/misc/changelog.Debian.gz",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../icons/128x128@2x.png",
    "usr/share/icons/brot3.png",
    "644",
  ],
  [
    "misc/brot3.desktop",
    "usr/share/applications/",
    "644",
  ],
]

[package.metadata.bundle.bin.brot3]
name = "brot3"
identifier = "com.crazyscot.brot3"
icon = ["icons/*"]
category = "GraphicsAndDesign"
# Don't forget to run cargo bundle --no-default-features ...
# N.B. README, etc, do not live in the bundle; they travel outboard as nobody ever looks inside the .app

[package.metadata.cargo-machete]
ignored = [
  "build-print", # used by build.rs
  "cfg_aliases", # used by build.rs
  "image", # used as a mixin, not directly referenced
]

[package.metadata.cargo-shear]
ignored = [
  "image", # used as a mixin, not directly referenced
]
