[package]
name = "brot3-ui"
version.workspace = true
authors.workspace = true
default-run = "brot3"
edition.workspace = true
license.workspace = true
publish = false
description = "Interactive fractal explorer"

[[bin]]
name = "brot3"
test = false
doc = false
bench = false

[lib]
test = false
doc = false
doctest = false
bench = false

[features]
default = ["ui", "use-compiled-tools"]
## Allow runtime edits to the shader code without having to rebuild the entire UI.
## Note that this feature needs to be able to find librustc_codegen_spirv.so at runtime.
## `cargo run` usually gets it right, but when running the binary you can specify the path
##  with `--spirv-tools=/path/to/librustc_codegen_spirv.so`.
hot-reload-shader = ["ui", "easy-shader-runner/hot-reload-shader"]
## Runtime compilation uses spirv-tools binaries (spirv-as, spirv-link, etc) installed in PATH, instead of
## compiling and linking the spirv-tools C++ code. `apt-get install spirv-tools` or equivalent.
use-installed-tools = ["easy-shader-runner?/use-installed-tools"]
## Runtime compilation compiles and links the C++ code for the spirv-tools binaries itself.
# If neither use-compiled-tools nor use-installed-tools are set, you need to the program uses whichever librustc_codegen_spirv.so it can find.
use-compiled-tools = ["easy-shader-runner?/use-compiled-tools"]
# special quasi-feature: detects that we're running in test mode, affects build script behaviour (suppresses building the shader)
_cfg_test = []
ui = [
  "easy-shader-runner",
  "egui_extras",
  "rfd",
  "dirs",
  "chrono",
  "scopeguard",
]

[dependencies]
brot3-lib = { workspace = true }
bytemuck = { workspace = true }
chrono = { workspace = true, features = ["clock"], optional = true }
clap = { workspace = true, features = ["derive", "wrap_help"] }
derive_more = { workspace = true, default-features = false, features = ["debug"] }
dirs = { workspace = true, optional = true }
easy-cast = { workspace = true, features = ["std"] }
egui_extras = { workspace = true, features = ["image"], optional = true }
env_logger = { workspace = true }
futures = { workspace = true, features = ["executor"] }
futures-channel = { workspace = true }
glam = { workspace = true }
# image is indirectly used, for unpicking PNGs
image = { workspace = true, features = ["png"] }
itertools = { workspace = true }
log = { workspace = true }
mimalloc = { workspace = true }
png = { workspace = true }
rfd = { workspace = true, optional = true }
scopeguard = { workspace = true, optional = true }
serde_json.workspace = true
strum = { workspace = true, features = ["std"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
wgpu = { workspace = true, default-features = false, features = ["spirv", "vulkan", "dx12", "metal"] }

[target.'cfg(not(any(target_arch = "wasm32")))'.dependencies]
easy-shader-runner = { workspace = true, default-features = false, optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
# CAUTION: wasm builds are not currently tested.
# wasm-bindgen-futures = "0.4.55"
easy-shader-runner = { workspace = true, default-features = false, features = ["emulate_constants"], optional = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true, features = ["Win32_System_Console"] }

[build-dependencies]
build-print = { workspace = true }
dunce = { workspace = true }
strum = { workspace = true, features = ["std", "derive"] }

[dev-dependencies]
average = { workspace = true }
brot3-ui = { path = ".", features = ["_cfg_test"] }

[lints]
workspace = true

[package.metadata.deb]
name = "brot3"
default-features = false # no runtime compilation
section = "mathematics"
extended-description = """\
An interactive fractal explorer that uses the GPU.
"""
assets = [
  [
    "target/release/brot3",
    "usr/bin/",
    "755",
  ],

  [
    "../README.md",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../LICENSE",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../target/misc/changelog.md.gz",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../target/misc/changelog.Debian.gz",
    "usr/share/doc/brot3/",
    "644",
  ],
  [
    "../icons/128x128@2x.png",
    "usr/share/icons/brot3.png",
    "644",
  ],
  [
    "misc/brot3.desktop",
    "usr/share/applications/",
    "644",
  ],
]

[package.metadata.bundle.bin.brot3]
name = "brot3"
identifier = "com.crazyscot.brot3"
icon = ["icons/*"]
category = "GraphicsAndDesign"
# Don't forget to run cargo bundle --no-default-features ...
# N.B. README, etc, do not live in the bundle; they travel outboard as nobody ever looks inside the .app

[package.metadata.cargo-machete]
ignored = [
  "build-print", # used by build.rs
  "dunce", # build.rs
  "image", # used as a mixin, not directly referenced
]

[package.metadata.cargo-shear]
ignored = [
  "image", # used as a mixin, not directly referenced
]
