name: build

on:
  workflow_call:
    inputs:
      release_workflow:
        type: boolean
        default: false
        description: Build for all supported platforms. (If false, builds only the CI subset.)
      save_cache:
        type: boolean
        default: true

permissions: {}

# N.B. github runners have `rustup set profile minimal` by default

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  BROT3_RUST_VERSION: nightly-2026-04-11
  # BROT3_RUST_VERSION should match the version in rust-toolchain.toml & across all workflows

jobs:
  shader_builder:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - name: Base toolchain
        uses: ./.github/actions/toolchain
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}

      # This job builds tooling for the shader job. Note that shader-builder is a thin wrapper around spirv_builder.
      # We also cache the built artifacts, so include as an extra key the hash of the crate source tree.
      # If the cache is hot, we short-circuit the build process and simply re-ship the cached artifacts.
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        id: rust-cache
        with:
          save-if: ${{ inputs.save_cache && github.ref_type != 'tag' }}
          cache-directories: .temp/sb
          key: ${{ hashFiles('shader_builder/**') }}

      - name: Determine build status
        id: do-build
        run: |
          echo Cache hit status: Rust ${{ steps.rust-cache.outputs.cache-hit }}.
          do_build=${{ (steps.rust-cache.outputs.cache-hit != 'true') && '1' || '0' }}
          echo RCC cache hit: ${{ steps.rust-cache.outputs.cache-hit }} : ${{ steps.rust-cache.outputs.cache-hit == 'true' }}
          echo do-build decision: $do_build
          echo do-build=$do_build >> $GITHUB_OUTPUT

      # Build and tooling actions (gated by the status check)
      # N.B. We don't need to install the spirv-tools .deb here, as we're not actually using them in this job
      - uses: ./.github/actions/toolchain
        if: ${{ steps.do-build.outputs.do-build == '1' }}
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}
          components: rust-src,rustc-dev,llvm-tools
      - name: build
        if: ${{ steps.do-build.outputs.do-build == '1' }}
        run: |
          rm -rf .temp/sb
          cargo build -p shader_builder --locked --release --no-default-features -F use-installed-tools
      - name: assemble upload
        if: ${{ steps.do-build.outputs.do-build == '1' }}
        run: mkdir -p .temp/sb && cp target/release/shader_builder target/release/librustc_codegen_spirv.so .temp/sb/

      # Send the artifact, whether we built it or it came from cache.
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: shader_builder
          path: .temp/sb/*
          if-no-files-found: error
        if: ${{ !cancelled() }}

  shader:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: shader_builder
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - name: Base toolchain
        uses: ./.github/actions/toolchain
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}

      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        id: rust-cache
        with:
          save-if: ${{ github.ref_type != 'tag' }}
          cache-directories: .temp/shader
          key: ${{ hashFiles('lib/**') }}
      - name: Determine build status
        id: do-build
        run: |
          echo Cache hit status: Rust ${{ steps.rust-cache.outputs.cache-hit }}
          do_build=${{ (steps.rust-cache.outputs.cache-hit != 'true') && '1' || '0' }}
          echo do-build decision: $do_build
          echo do-build=$do_build >> $GITHUB_OUTPUT
          ls -lR .temp/shader || true

      # Tool installation and shader build are gated by the status check
      - uses: ./.github/actions/toolchain
        if: ${{ steps.do-build.outputs.do-build == '1' }}
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}
          components: rust-src,rustc-dev,llvm-tools
      - name: Download shader_builder
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        if: ${{ steps.do-build.outputs.do-build == '1' }}
        with:
          name: shader_builder
          path: ${{ github.workspace }}/.temp/shader_builder
      - name: Install spirv-tools, fix permissions
        run: |
          sudo apt update && sudo apt install spirv-tools
          ls -lR .temp ; chmod -v +x ${{ github.workspace }}/.temp/shader_builder/*
        if: ${{ steps.do-build.outputs.do-build == '1' }}
      - name: build shader
        if: ${{ steps.do-build.outputs.do-build == '1' }}
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.temp/shader_builder
        run: |
          pwd; ls -lR .temp/shader_builder
          ./.temp/shader_builder/shader_builder
          mkdir -p .temp/shader
          cp target/spirv-builder/spirv-unknown-vulkan1.1/release/deps/*.spv .temp/shader

      # This step is unconditional so the result can be used by later jobs
      - name: Upload artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: brot3_lib.spv
          path: .temp/shader/
          if-no-files-found: error
        # Try to upload on error, to provide maximum useful information for a human diagnostic
        if: ${{ !cancelled() }}

  define-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.define.outputs.matrix }}
    steps:
      # There's no easy way in yml to conditionally include matrix entries, so
      # this Python generates the structure in JSON, which we parse below.
      - name: Define matrix
        id: define
        shell: python
        env:
          RELEASE_WORKFLOW: ${{ inputs.release_workflow }}
        run: |
          #!/usr/bin/env/python3
          import os
          import json

          GITHUB_OUTPUT = os.getenv('GITHUB_OUTPUT')
          RELEASE_WORKFLOW = os.getenv('RELEASE_WORKFLOW')

          PLATFORMS={
            'linux': 'linux',
            'apple-darwin': 'mac',
            'windows': 'windows',
          }

          def combo(triple, runs_on, tools='', rust_components='', cache=False):
            # triple is a Rust target triple
            # platform is one of mac, windows, linux
            (arch, rest) = triple.split('-', 1)
            platform = next((v for k, v in PLATFORMS.items() if k in rest), None)
            if platform is None:
              raise RuntimeError(f'Unknown platform in target triple {triple}')
            short_target = f'{platform}-{arch}'

            return {
              'target': triple, 'platform': platform, 'runs_on': runs_on,
              'tools': tools, 'rust_components': rust_components, 'cache': cache,
              'arch': arch, 'short_target': short_target,
            }

          print('::group::Building matrix')

          # Combinations to always include in the matrix
          matrix = [combo('x86_64-unknown-linux-gnu', 'ubuntu-22.04', 'cargo-deb', '', True)]

          # Combinations to include only on release builds
          if RELEASE_WORKFLOW == 'true':
            matrix.extend([
              combo('aarch64-apple-darwin', 'macos-15'),
              combo('x86_64-apple-darwin', 'macos-15-intel'),
              combo('x86_64-pc-windows-msvc', 'windows-2025'),
          ])

          print(f'{json.dumps(matrix, indent=2)}')
          print('::endgroup::')

          print('::group::Writing output')
          try:
              with open(GITHUB_OUTPUT, 'w') as file:
                  file.write(f'matrix={json.dumps(matrix)}')
          except Exception as e:
              print(f'::error::Failed to write the GitHub output file: {e}')
              exit(1)
          print('::endgroup::')

  ui:
    needs:
      - define-matrix
      - shader
    strategy:
      matrix:
        include: ${{ fromJSON(needs.define-matrix.outputs.matrix) }}
    runs-on: ${{ matrix.runs_on }}
    env:
      ARCHIVE_SUFFIX: ${{ matrix.platform == 'windows' && 'zip' || 'tar.gz' }}
      # Is the binary upload raw ? (Mac binaries need to be wrapped into the app package format.)
      RAW_OR_BINARY_MARKER: ${{ matrix.platform == 'mac' && '-raw' || '-binary' }}
      RAW_OR_EMPTY_MARKER: ${{ matrix.platform == 'mac' && '-raw' || '' }}
      # Downloaded artifact from an earlier job - set up by download-artifact action
      BROT3_PREBUILD_SHADERS_DIR: ${{ github.workspace }}/.temp/prebuilt-shader
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      # N.B. We do not use the local toolchain action here, because it overwrites rust-toolchain.toml which causes the build to be marked as dirty.
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.BROT3_RUST_VERSION }}
          components: ${{ join(env.Components, ',') }}
        env:
          Components:
            rust-src,rustc-dev,llvm-tools
            ${{ matrix.rust_components }}

      - name: install additional tools
        if: ${{ matrix.tools }}
        uses: taiki-e/install-action@dfcb1ee29051d97c8d0f2d437199570008fd5612 # v2.65.15
        # this action is used in multiple places
        with:
          tool: ${{ matrix.tools }}
          checksum: true
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          save-if: ${{ inputs.save_cache && github.ref_type != 'tag' }}
      - name: Download shader
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: brot3_lib.spv
          path: ${{ env.BROT3_PREBUILD_SHADERS_DIR }}

      - name: status check
        run: git status --porcelain
      - name: build
        id: prebuild
        # We need to run this to get the version file, so we can feed that to build-binary...
        # CAUTION: This cargo invocation must match that used by the build-binary step.
        run: cargo build --release --bin brot3 --locked --package brot3-ui --verbose
      - name: extract version
        id: version
        shell: python
        run: |
          import os
          with open('./target/release/brot3.build-version.txt', 'r') as f:
            version = f.read().strip()
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f'version={version}')
      - name: build binary package
        uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6 # v1.32.2
        id: build-binary
        with:
          bin: brot3
          dry-run: true
          dry-run-intended: true
          # Fake up a ref to control the output directory/archive name
          ref: refs/tags/${{ steps.version.outputs.version }}
          include: "README.md,LICENSE,CHANGELOG.md"
          leading-dir: true
          locked: true
          package: brot3-ui
          #features: ui
          # CAUTION: These options must lead to a cargo invocation that matches that of the build-binary step.
          # If unsure, check this step's output log.
          # For this INNER archive, we use -raw on Mac and otherwise no suffix.
          archive: $bin_$tag-${{ matrix.short_target }}${{ env.RAW_OR_EMPTY_MARKER }}
          # TODO, someday: include codesign options on mac
      - name: Upload binary
        if: ${{ success() || failure() }}
        # always try to do this, it allows the package to be checked
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          # For this OUTER archive, we use -raw on Mac and -binary elsewhere.
          # The inner and outer names must be different to avoid archive overwrites, confusion
          # and derision.
          # It is less important on mac, because the raw isn't the final stage; that's -app.
          # (Note that while all the outers are .zip, the inners on non-Windows platforms are .tar.gz.)
          name: brot3_${{ steps.version.outputs.version }}-${{ matrix.short_target }}${{ env.RAW_OR_BINARY_MARKER }}
          path: ${{ steps.build-binary.outputs.archive }}.${{ env.ARCHIVE_SUFFIX }}

      - name: debian packaging
        if: ${{ matrix.platform == 'linux' }}
        id: build_deb
        run: cargo xtask debian --no-build
        # this writes the output 'deb=<file>'
      - name: upload deb
        if: ${{ matrix.platform == 'linux' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: brot3_${{ steps.version.outputs.version }}-deb-${{ matrix.runs_on }}
          path: ${{ steps.build_deb.outputs.deb }}

      - name: create mac Info.plist
        if: ${{ matrix.platform == 'mac' }}
        shell: python
        env:
          PACKAGE_VERSION: ${{ steps.version.outputs.version }}
        run: |
          import os
          import re
          from string import Template
          from time import strftime, gmtime

          with open('ui/misc/Info.plist.tmpl') as f:
            template = Template(f.read())

          # CFBundleVersion can only be Major.Minor.Patch and is limited to AAAA.BB.CC
          build_date = strftime('%Y.%m.%d', gmtime())

          # PACKAGE_VERSION is git describe output; e.g. v3.0.0-87-g99970eb-dirty
          # CFBundleShortVersionString can only be Major.Minor.Patch
          match = re.search(r'v?(\d+\.\d+\.\d+)', os.environ['PACKAGE_VERSION'])
          semver = match.group(1)

          result = template.substitute(
            SEMVER=semver,
            BUILD_DATE=build_date,
          )
          with open('target/Info.plist', 'w') as f:
            f.write(result)

      - name: prepare mac app bundle
        id: bundle-mac
        if: ${{ matrix.platform == 'mac' }}
        run: |
          STEM=${{ steps.build-binary.outputs.archive }}
          WORKDIR=target/appbundle
          # unpack the raw
          mkdir -p ${WORKDIR}
          tar -C ${WORKDIR} -zxf ${STEM}.tar.gz
          # workdir is $STEM
          # TEMP debug:
          ls -l ${WORKDIR}
          ls -l ${WORKDIR}/${STEM}

          # rearrange
          mkdir -p ${WORKDIR}/${STEM}/brot3.app/Contents/{MacOS,Resources}
          mv ${WORKDIR}/${STEM}/brot3 ${WORKDIR}/${STEM}/brot3.app/Contents/MacOS/
          # copy in additional files
          cp target/Info.plist ${WORKDIR}/${STEM}/brot3.app/Contents/
          cp icons/icon.icns ${WORKDIR}/${STEM}/brot3.app/Contents/Resources/
          # rename the stem
          NEWSTEM=${STEM/-raw/}
          ( cd ${WORKDIR} && mv ${STEM} ${NEWSTEM} )
          # zip it up
          ( cd ${WORKDIR} && zip -r ${NEWSTEM}.zip ${NEWSTEM} )
          echo "zipfile=${WORKDIR}/${NEWSTEM}.zip" >> $GITHUB_OUTPUT

      - name: upload mac app bundle
        if: ${{ matrix.platform == 'mac' }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: brot3_${{ steps.version.outputs.version }}-${{ matrix.short_target }}-app
          path: ${{ steps.bundle-mac.outputs.zipfile }}
      # TODO: Someday, make a DMG

  ui-variants:
    # These builds are not shipped, but confirming that they haven't broken is valuable.
    # This is a separate build due to its size. (The hot-reload-shader feature flag pulls in spirv-tools.)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - shader
    env:
      BROT3_PREBUILD_SHADERS_DIR: ${{ github.workspace }}/.temp/prebuilt-shader
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: ./.github/actions/toolchain
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}
          components: rust-src,rustc-dev,llvm-tools
      - name: Download shader
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: brot3_lib.spv
          path: ${{ env.BROT3_PREBUILD_SHADERS_DIR }}
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          save-if: ${{ inputs.save_cache && github.ref_type != 'tag' }}
      # As these builds are not shipped, build as debug builds for speed.
      # no-default-features means we don't build librustc_codegen_spirv.
      # We don't even need to install the spirv-tools deb in this runner instance, as we don't run them (not right now,
      # but maybe unit tests in future? If so, use the artifact from shader_builder.)
      - name: build (headless)
        run: cargo build --bin brot3 --locked --package brot3-ui --verbose --no-default-features
      - name: build (hot-reload)
        # As this build is not shipped, build it as a debug build for speed.
        # no-default-features means we don't build librustc_codegen_spirv.
        # We don't even need to install the spirv-tools deb in this runner instance, as we don't run them (not right now,
        # but maybe unit tests in future? If so, use the artifact from shader_builder.)
        run: cargo build --bin brot3 --locked --package brot3-ui --verbose --no-default-features -F hot-reload-shader -F ui
