name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.78.0
  # remember to update RUST_TOOLCHAIN in release.yml too

jobs:
  rust:
    strategy:
      matrix:
        platform: [ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        components: clippy, rustfmt
        toolchain: ${{ env.RUST_TOOLCHAIN }}
    - uses: Swatinem/rust-cache@v2
    - run: sudo apt-get update && sudo apt-get -y --no-install-recommends install curl wget file mold libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    - name: Code style check
      run: cargo fmt --all -- --check
    # we used to use actions/cache@v4
    - name: Build
      run: cargo build --all-targets --locked
    # we want to ensure the benches build... but we already do that in debug with --all-targets
    - name: Test
      run: cargo test
    - name: Lint
      # N.B. --all-features doesn't build; we're not using tauri custom-protocol
      run: cargo clippy --all-targets
