name: CI

on:
  push:
  workflow_dispatch:

permissions: {}

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  BROT3_RUST_VERSION: nightly-2026-04-11
  # BROT3_RUST_VERSION should match the version in rust-toolchain.toml & across all workflows

# N.B. github runners have `rustup set profile minimal` by default

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release_workflow: false

  cargo-deny:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
        with:
          persist-credentials: false
      - name: cargo deny
        uses: EmbarkStudios/cargo-deny-action@3fd3802e88374d3fe9159b834c7714ec57d6c979 # 2.0.14
        with:
          command: check ${{ matrix.checks }}
          rust-version: ${{ env.BROT3_RUST_VERSION }}
          # N.B. the cargo-deny-action container image installs 1.85.0 by default

  cargo-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: ./.github/actions/toolchain
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}
          components: rustfmt
      - run: cargo fmt --all -- --check

  coverage:
    name: coverage (selected)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: ./.github/actions/toolchain
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}
          components: llvm-tools
      - uses: taiki-e/install-action@dfcb1ee29051d97c8d0f2d437199570008fd5612 # v2.65.15
        with:
          tool: cargo-llvm-cov
          checksum: true
      # 2025-10-26: a hot cache saves only around 15 seconds, this is not worthwhile at present
      #- uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: mkdir -p target/coverage
      - name: Run selected package tests with coverage analysis
        run:
          # Note that we do NOT run +nightly here, as we installed an explicit nightly version above.
          cargo llvm-cov -p brot3-lib --all-features --doctests --lcov --output-path lcov.info --locked
      - name: Upload coverage artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: lcov.info
          path: lcov.info
      - name: Send result to codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          #files: lcov.info # not needed, it autodetects
          #verbose: true # not needed
          name: lcov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  checks-stable-suite:
    name: checks (stable suite)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      # This job runs all its checks without stopping (unless cancelled)
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: ./.github/actions/toolchain
        with:
          channel: stable
      - uses: taiki-e/install-action@dfcb1ee29051d97c8d0f2d437199570008fd5612 # v2.65.15
        with:
          tool: typos,dprint,cargo-machete,cargo-shear
          checksum: true
      - run: typos
        if: ${{ !cancelled() }}
      - run: dprint check --list-different
        # to fix: dprint fmt
        if: ${{ !cancelled() }}
      - run: dprint fmt --diff
        if: ${{ failure() }}
      - run: cargo +stable machete --with-metadata
        if: ${{ !cancelled() }}
      - run: cargo +stable shear --locked
        if: ${{ !cancelled() }}

  clippy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      RUSTGPU_SKIP_TOOLCHAIN_CHECK: 1
      # suppress the shader build as this build is not shipped
      BROT3_SUPPRESS_SHADER_BUILD: 1
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
      - uses: ./.github/actions/toolchain
        with:
          channel: ${{ env.BROT3_RUST_VERSION }}
          components: clippy,rustc-dev
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - name: clippy (no-default-features)
        run: cargo clippy --locked --no-deps --all-targets -p brot3-lib -p brot3-ui --no-default-features
      - name: clippy (ui + hot-reload)
        run: cargo clippy --locked --no-deps --all-targets -p brot3-lib -p brot3-ui -F ui -F hot-reload-shader
        if: ${{ !cancelled() }}
      # There's no need to run clippy on use-installed-tools or use-compiled-tools as they are simple passthroughs
