name: CI

on:
  push:
  workflow_dispatch:

permissions: {}

env:
  CARGO_TERM_COLOR: always
  CLICOLOR_FORCE: 1
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  BROT3_RUST_VERSION: nightly-2025-06-30
  # BROT3_RUST_VERSION should match the version in rust-toolchain.toml & across all workflows

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release_workflow: false

  cargo-deny:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    # Prevent sudden announcement of a new advisory from failing ci:
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: set toolchain override
        run: cp -f rust-toolchain-fmt.toml rust-toolchain.toml
      - name: cargo deny
        uses: EmbarkStudios/cargo-deny-action@76cd80eb775d7bbbd2d80292136d74d39e1b4918 # 2.0.14
        with:
          command: check ${{ matrix.checks }}
          rust-version: "nightly-2025-06-30"
          # N.B. the cargo-deny-action container image installs 1.85.0 by default

  cargo-fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: set toolchain override
        run: cp -f rust-toolchain-fmt.toml rust-toolchain.toml
      - name: Install Rust
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.BROT3_RUST_VERSION }}
          components: rustfmt
      - run: cargo fmt --all -- --check

  coverage:
    name: coverage (selected)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set minimal profile # no fmt or clippy
        run: rustup set profile minimal
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561
        with:
          toolchain: ${{ env.BROT3_RUST_VERSION }}
      - uses: taiki-e/install-action@cf46383a970594553a83cc6140075ef6a7f54dee # v2.62.64
        with:
          tool: cargo-llvm-cov
          checksum: true
      # 2025-10-26: a hot cache saves only around 15 seconds, this is not worthwhile at present
      #- uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
      - run: mkdir -p target/coverage
      - name: Run selected package tests with coverage analysis
        run:
          # See note in scripts/coverage for why --no-cfg-coverage is necessary.
          # Note that we do NOT run +nightly here, as we installed an explicit nightly version above.
          cargo llvm-cov -p shader -p shader_common -p util --all-features --doctests --lcov --output-path lcov.info --no-cfg-coverage --locked
      - name: Upload coverage artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v4.6.2
        with:
          name: lcov.info
          path: lcov.info
      - name: Send result to codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          #files: lcov.info # not needed, it autodetects
          #verbose: true # not needed
          name: lcov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  checks-stable-suite:
    name: checks (stable suite)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # This job runs all its checks without stopping (unless cancelled)
      - uses: actions/checkout@v6
      - uses: taiki-e/install-action@cf46383a970594553a83cc6140075ef6a7f54dee # v2.62.64
        with:
          tool: typos,dprint,cargo-machete
          checksum: true
      - run: typos
        if: ${{ !cancelled() }}
      - run: dprint check --list-different
        # to fix: dprint fmt
        if: ${{ !cancelled() }}
      - run: dprint fmt --diff
        if: ${{ failure() }}
      - run: cargo +stable machete --with-metadata
        if: ${{ !cancelled() }}
