name: Rust

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Toolchain
      run: rustup toolchain install stable --profile minimal --no-self-update
    - name: Code style check
      run: cargo fmt --all -- --check --verbose
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    # we used to use actions/cache@v4
    - name: Build
      run: cargo build --verbose
    - name: Build tests
      run: cargo test --verbose --no-run
    - name: Build benchmarks
      run: cargo bench --no-run
    - name: Run tests
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose --all-features --all-targets
