name: Rust

on:
  push:
    #branches: [ "main" ]
  pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Toolchain
      run: rustup toolchain install stable --profile minimal --no-self-update
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
    # we used to use actions/cache@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Format check
      run: cargo fmt --all -- --check --verbose
    - name: Run checks
      run: cargo check --verbose
    - name: Extra checks
      run: cargo clippy --verbose
    - name: Compile-check benchmarks
      run: cargo bench --no-run
